CREATE OR REPLACE FORCE VIEW "AEROFRANCE_LIAO"."VIEW_COMMANDEGLOBALE" ("COMGLOBNUM", "FOURNUM", "COMGLOBDATE", "COMGLOBETAT") AS 
SELECT "COMGLOBNUM","FOURNUM","COMGLOBDATE","COMGLOBETAT"
FROM CHEF_GUO.COMMANDEGLOBALE
WHERE FOURNUM = 4;
 

CREATE OR REPLACE TRIGGER "AEROFRANCE_LIAO"."PREPARATION_COMGLOB" 
INSTEAD OF UPDATE ON VIEW_COMMANDEGLOBALE 
REFERENCING OLD AS A NEW AS N 
FOR EACH ROW
BEGIN
    if :n.comglobetat = 'en cours de préparation' then
        ETAT_PREPARATION(:n.comglobnum);
    end if;
END;
/
ALTER TRIGGER "AEROFRANCE_LIAO"."PREPARATION_COMGLOB" ENABLE;