CREATE OR REPLACE FORCE VIEW "AEROFRANCE_LIAO"."VIEW_BONLIVRAISON" ("BONLIVNUM", "PRODNUM", "QTELIV", "QTEREFUS") AS 
SELECT bonlivnum, prodnum, qteliv, qterefus   
FROM CHEF_GUO.VIEW_BONLIV
WHERE fournum = 4;