CREATE OR REPLACE FORCE VIEW "AEROFRANCE_LIAO"."VIEW_FOURNIR" ("PRODNUM", "HISTODATE", "PROPRIX", "SEUIL") AS 
SELECT "PRODNUM","HISTODATE","PROPRIX","SEUIL"  
FROM CHEF_GUO.FOURNIR
WHERE FOURNUM = 4;
 

CREATE OR REPLACE TRIGGER "AEROFRANCE_LIAO"."MODIFIER_FOURNIR" 
INSTEAD OF UPDATE ON VIEW_FOURNIR 
REFERENCING OLD AS A NEW AS N 
FOR EACH ROW
BEGIN
    if to_char(:n.histodate, 'DD/MM/YY') = to_char(sysdate, 'DD/MM/YY') then
        modification_fournir(:n.prodnum, :n.histodate, :n.proprix, :n.seuil);
    end if;
END;
/
ALTER TRIGGER "AEROFRANCE_LIAO"."MODIFIER_FOURNIR" ENABLE;