create or replace PROCEDURE MODIFICATION_FOURNIR 
(
  P_PRODNUM IN NUMBER, 
  P_DATE IN DATE,
  P_PRIX IN NUMBER,
  P_SEUIL IN NUMBER  
) AS pragma AUTONOMOUS_TRANSACTION;
BEGIN
    update CHEF_GUO.fournir SET PROPRIX = P_PRIX, SEUIL = P_SEUIL 
    where FOURNUM = 4
    and HISTODATE = P_DATE
    and PRODNUM = P_PRODNUM;
    commit;
END MODIFICATION_FOURNIR;