CREATE OR REPLACE FORCE VIEW "CHEF_GUO"."VIEW_BONLIV" ("FOURNUM", "BONLIVNUM", "PRODNUM", "QTELIV", "QTEREFUS") AS 
SELECT fournum, b.bonlivnum, l.prodnum, l.qteliv, l.qterefus  
FROM CHEF_GUO.BONLIVRAISON b, CHEF_GUO.LIVRER l, CHEF_GUO.COMMANDEGLOBALE com
WHERE b.comglobnum = com.comglobnum
and b.bonlivnum = l.bonlivnum(+);


CREATE OR REPLACE FORCE VIEW "CHEF_GUO"."VIEW_COLIS" ("COLNUM", "CHARNUM", "PRODNUM", "COMNUM", "COLETAT", "QTELIV") AS 
SELECT colnum, charnum, prodnum, comnum, coletat, qteliv   
FROM colis;


CREATE OR REPLACE FORCE VIEW "CHEF_GUO"."VIEW_COMMANDE" ("COMNUM", "COMETAT") AS 
SELECT comnum, cometat  
FROM commande;


CREATE OR REPLACE FORCE VIEW "CHEF_GUO"."VIEW_ETATCHARGEMENT" ("CHARNUM", "CHARETAT") AS 
SELECT CHARNUM, CHARETAT  
FROM CHARGEMENT;


CREATE OR REPLACE FORCE VIEW "CHEF_GUO"."VIEW_LIVRER" ("PRODNUM", "BONLIVNUM", "QTELIV") AS 
SELECT PRODNUM, BONLIVNUM, QTELIV  
FROM LIVRER;